#!/usr/bin/env python3
"""Compile the repository's real Swift codecs in isolation and generate/verify fixtures.

This does not require building the app or SwiftTerm. Only platform helpers with no wire
semantics (trace, keychain lookup, legacy defaults, display formatting) are stubbed.
"""
from pathlib import Path
import argparse
import hashlib
import json
import os
import subprocess
import tempfile

HERE = Path(__file__).resolve().parent
ROOT = HERE.parents[1]


def source(name):
    return (ROOT / name).read_text()


def between(name, start, end):
    text = source(name)
    return text[text.index(start):text.index(end, text.index(start))]


def swift_source():
    pieces = ["import Foundation\nimport CryptoKit\nimport Compression\n"]
    pieces.append(between("Sources/ConfigurationSync.swift", "enum ConfigurationSyncError", "enum SyncChoice"))
    pieces.append(between("Sources/LocalConfigurationTransfer.swift", "struct LocalConfigurationPackage", "@MainActor enum LocalConfigurationExport"))
    pieces.append(between("Vendor/SwiftTerm/Sources/SwiftTerm/DisplaySnapshot.swift", "public struct TerminalDisplaySnapshot", "extension Terminal"))
    pieces.append(source("Sources/RecordingFormat.swift").replace("import SwiftTerm", ""))
    pieces.append(between("Sources/RDPModels.swift", "enum RDPKeyboardMode", "/// RDP stays a separate entity"))
    pieces.append(between("Sources/ProfessionalConnections.swift", "struct ConnectionEndpoint", "enum ConnectionFailureStage"))
    pieces.append(between("Sources/ProfessionalConnections.swift", "enum ConnectionRouteError", "enum ResolvedCredential"))
    pieces.append(between("Sources/WorkbenchConnectionModels.swift", "enum WorkbenchConnectionError", "private func connectionTags"))
    pieces.append(between("Sources/WorkbenchConnectionModels.swift", "struct SSHAdvancedSettingsDraft", "@Model final class SSHAdvancedSettingsRecord"))
    pieces.append(between("Sources/AIProviders.swift", "enum AIProviderID", "protocol AICredentialStore"))
    pieces.append(between("Sources/AIModels.swift", "enum AIError", "struct AIConfiguration"))
    pieces.append(between("Sources/AIClient.swift", "struct AIWireMessage", "enum AIRequestBuilder"))
    limits = [line.strip() for line in source("Sources/AIClient.swift").splitlines() if line.strip().startswith(("static let eventLimit", "static let responseLimit"))]
    assert len(limits) == 2
    pieces.append("enum AIStreamDecoder { " + "; ".join(limits) + " }")
    pieces.append(source("Sources/AIProviderAdapter.swift"))
    pieces.append(between("Sources/Models.swift", "struct CPUCoreMetric", "    var memoryUsage: Double") + "}\n")
    pieces.append(source("Sources/Services.swift").split("enum MonitoringResponseParser", 1)[1].join(["enum MonitoringResponseParser", ""]))
    pieces.append(between("Sources/SessionTransfer.swift", "enum AuthenticationHint", "    var title: String") + "}\n")
    pieces.append(between("Sources/SessionTransfer.swift", "struct SessionTransferRecord", "    init(server: ServerRecord)") + "}\n")
    pieces.append(between("Sources/SessionTransfer.swift", "struct ServerDashSessionDocument", "/// Deliberately does not conform"))
    pieces.append("""
enum PrivacySettings { static let connectTimeout = 8.0 }
enum DisplayFormat { static func integer(_ value: Int) -> String { String(value) } }
enum KeychainService { static func secret(account: String) throws -> String? { nil } }
enum MonitoringError: Error { case invalidResponse(String) }
enum PerformanceTrace {
    enum Kind { case monitorParse }
    static func begin(_ kind: Kind) -> Int { 0 }
    static func end(_ token: Int) {}
}
""")
    pieces.append((HERE / "FixtureMain.swift").read_text())
    return "\n".join(pieces)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="Check generated fixtures without changing tracked files")
    parser.add_argument("--verify-rust", type=Path, help="Verify rust-local.json, rust-sync.configsync, rust-recording.sdrec generated by Rust tests")
    args = parser.parse_args()
    build = ROOT / ".build" / "contracts"
    build.mkdir(parents=True, exist_ok=True)
    main_file = build / "main.swift"
    main_file.write_text(swift_source())
    binary = build / "swift-contracts"
    subprocess.run(["xcrun", "swiftc", "-swift-version", "5", "-module-cache-path", str(build / "module-cache"), str(main_file), "-o", str(binary)], check=True, cwd=ROOT)
    if args.verify_rust:
        subprocess.run([str(binary), "verify-rust", str(args.verify_rust.resolve())], check=True)
        return
    target = HERE / "fixtures"
    target.mkdir(exist_ok=True)
    with tempfile.TemporaryDirectory(prefix="serverdash-contracts-") as temporary:
        generated = Path(temporary)
        env = dict(os.environ, TZ="UTC", LANG="en_US.UTF-8")
        subprocess.run([str(binary), "generate", str(generated)], check=True, env=env)
        manifest = "".join(f"{hashlib.sha256(p.read_bytes()).hexdigest()}  {p.name}\n" for p in sorted(generated.iterdir()))
        (generated / "SHA256SUMS").write_text(manifest)
        if args.check:
            # JSONEncoder does not promise key order. LZFSE block offsets can
            # therefore change without a wire-contract change. The real decoder
            # validates each checksum/footer before comparing canonical events.
            subprocess.run([str(binary), "compare-recordings", str(target), str(generated)], check=True)
            for line in (target / "SHA256SUMS").read_text().splitlines():
                digest, name = line.split("  ", 1)
                assert hashlib.sha256((target / name).read_bytes()).hexdigest() == digest, f"Fixture checksum mismatch: {name}"
        for path in generated.iterdir():
            if args.check:
                if path.name in {"SHA256SUMS", "swift-recording.sdrec", "swift-recording.partial"}:
                    continue
                if path.name == "swift-metadata.json":
                    actual, expected = json.loads(path.read_bytes()), json.loads((target / path.name).read_bytes())
                    actual.pop("recordingKeyframeOffset"); expected.pop("recordingKeyframeOffset")
                    assert actual == expected, f"Fixture drift: {path.name}"
                else:
                    assert (target / path.name).read_bytes() == path.read_bytes(), f"Fixture drift: {path.name}"
            else:
                (target / path.name).write_bytes(path.read_bytes())
    print("Swift contract fixtures verified" if args.check else "Swift contract fixtures generated")


if __name__ == "__main__":
    main()
